### ISSUE TITLE
codereview for roc.py

### ISSUE THREAD

**Issue by ultinous-zssanta** [ultinous-bjenei/scripts#1]
1. Follow pep8 rules for imports (... and in every other case) https://pep8.org/#imports 
https://github.com/ultinous-bjenei/scripts/blob/5c7bb916d99e15ae14061c4799cdaf3266bd8f64/roc.py#L3-L13

2. Move argparse creation into a new function
https://github.com/ultinous-bjenei/scripts/blob/5c7bb916d99e15ae14061c4799cdaf3266bd8f64/roc.py#L31-L36

3. Use a single predicate for that:
```
def is_csv_file(f):
  return path.is_file(f) and path.splitext(file)[1] == ".csv"
```
https://github.com/ultinous-bjenei/scripts/blob/5c7bb916d99e15ae14061c4799cdaf3266bd8f64/roc.py#L44-L47

4. Move this into a new function and remove quasi-global variable dependency (precision, etc)
https://github.com/ultinous-bjenei/scripts/blob/5c7bb916d99e15ae14061c4799cdaf3266bd8f64/roc.py#L51-L58
https://github.com/ultinous-bjenei/scripts/blob/5c7bb916d99e15ae14061c4799cdaf3266bd8f64/roc.py#L126-L148

5. Use method chaining
https://github.com/ultinous-bjenei/scripts/blob/5c7bb916d99e15ae14061c4799cdaf3266bd8f64/roc.py#L87-L91
https://github.com/ultinous-bjenei/scripts/blob/5c7bb916d99e15ae14061c4799cdaf3266bd8f64/roc.py#L115-L116

6. Use cummax (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.cummax.html)
https://github.com/ultinous-bjenei/scripts/blob/5c7bb916d99e15ae14061c4799cdaf3266bd8f64/roc.py#L96-L99

7. Use to_numpy() instead of values (recommended: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html)
https://github.com/ultinous-bjenei/scripts/blob/5c7bb916d99e15ae14061c4799cdaf3266bd8f64/roc.py#L103-L105

8. Is there any documentation for this format?
https://github.com/ultinous-bjenei/scripts/blob/5c7bb916d99e15ae14061c4799cdaf3266bd8f64/roc.py#L69

9. [optional] Command line argument for delimiter?
https://github.com/ultinous-bjenei/scripts/blob/5c7bb916d99e15ae14061c4799cdaf3266bd8f64/roc.py#L79

**Comment by ghost** [comment]
Commit [b68a38e](https://github.com/ultinous-bjenei/scripts/commit/b68a38e5da55a7c451e52934ffb5d7614f2dbce1) tries to address these.
Thanks, good tips. Please take a look at the files in the **_detector_benchmark_** directory as well.
